spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapping
    username: root
    password: jiyodigital
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    