server:
  port: 8083
spring:
  application:
    name: store-service
  datasource:
    url: jdbc:mysql://localhost:3306/rcon
    username: root
    password: jiyodigital
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
