server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false #telling the server not to register himself in the service registry