server:
  port: 8084
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/rcon
    username: root
    password: jiyodigital
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  #security:
    #user:
     # name: john
      #password: john 
      