spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: jiyodigital
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#security:
#  user:
#    name: admin
#    password: admin